var rita = require('rita');

/*var rs = rita.RiString("The elephant took a bite!");
console.log(rs.features());*/

const markov = new rita.RiMarkov(3);
markov.loadText('Over the past two days I’ve played roughly 10 hours of Destiny 2, a video game in which players travel through space, marveling at how things can feel so familiar and yet so new.In some ways it’s just more Destiny. Here we are again, shooting aliens and watching the numbers go up. Yet Destiny 2 has fixed many of its predecessor’s shortcomings, both structurally and narratively, and as I play through the main story, I find myself invested in a way I never was before, thanks to fun writing and engaging missions. Although I’d caution against jumping to conclusions until the game’s been out for a while—remember, we didn’t really understand Destiny 1 until a few weeks after launch—I’ve been thrilled by what I’ve played so far. (Note: Kotaku will run our official review of Destiny 2 after we’ve checked out the raid, which launches on September 13.) For starters, there are real stakes. Destiny 2 opens with the destruction of the Tower, our central hub for the past three years, at the hands of a nasty Cabal commander named Ghaul, who drains your main character of his or her powers and sends you flying off a cliff. In a powerful, humbling sequence afterwards, you stumble around the neighboring Last City while trying to regain your lost abilities. Soon you’ll run into Suraya Hawthorne, a nomadic sniper and member of Destiny 2’s excellent cast of new characters, and eventually you’ll find yourself roaming through the game’s first map, the European Dead Zone. This is where Destiny 2’s unique world structure comes into play, and it’s one of the greatest changes Bungie has made. Rather than selecting a mission, zooming back to orbit, and then selecting another mission as you did in the first game, Destiny 2 lets you conduct all of your work from the field. To access each story mission, you’ll have to land at a planet’s loadout zone, track the point where that mission starts, and then walk over. Along the way, you might run into a public event and work with a group of players to take down a Fallen gang that’s trying to dig up currency from the land. Or you might decide to go do an optional “adventure” that’s sort of like a beefed up version of Destiny 1’s patrols, complete with proper stories and multiple phases.');
console.log(markov.generateSentences(2));
/*
Over the past two days I’ve played roughly 10 hours of Destiny 2, a video game in which players travel through space, marveling at how things can feel so familiar and yet so new.In some ways it’s just more Destiny. Here we are again, shooting aliens and watching the numbers go up. Yet Destiny 2 has fixed many of its predecessor’s shortcomings, both structurally and narratively, and as I play through the main story, I find myself invested in a way I never was before, thanks to fun writing and engaging missions. Although I’d caution against jumping to conclusions until the game’s been out for a while—remember, we didn’t really understand Destiny 1 until a few weeks after launch—I’ve been thrilled by what I’ve played so far. (Note: Kotaku will run our official review of Destiny 2 after we’ve checked out the raid, which launches on September 13.) For starters, there are real stakes. Destiny 2 opens with the destruction of the Tower, our central hub for the past three years, at the hands of a nasty Cabal commander named Ghaul, who drains your main character of his or her powers and sends you flying off a cliff. In a powerful, humbling sequence afterwards, you stumble around the neighboring Last City while trying to regain your lost abilities. Soon you’ll run into Suraya Hawthorne, a nomadic sniper and member of Destiny 2’s excellent cast of new characters, and eventually you’ll find yourself roaming through the game’s first map, the European Dead Zone. This is where Destiny 2’s unique world structure comes into play, and it’s one of the greatest changes Bungie has made. Rather than selecting a mission, zooming back to orbit, and then selecting another mission as you did in the first game, Destiny 2 lets you conduct all of your work from the field. To access each story mission, you’ll have to land at a planet’s loadout zone, track the point where that mission starts, and then walk over. Along the way, you might run into a public event and work with a group of players to take down a Fallen gang that’s trying to dig up currency from the land. Or you might decide to go do an optional “adventure” that’s sort of like a beefed up version of Destiny 1’s patrols, complete with proper stories and multiple phases.
*/
